# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdes\Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(400, 342)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pic/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calendar.setWindowIcon(icon)
        self.calendar = QtWidgets.QCalendarWidget(Calendar)
        self.calendar.setEnabled(True)
        self.calendar.setGeometry(QtCore.QRect(1, 0, 401, 251))
        self.calendar.setMinimumSize(QtCore.QSize(401, 251))
        self.calendar.setMaximumSize(QtCore.QSize(401, 251))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.calendar.setFont(font)
        self.calendar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.calendar.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(85, 170, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.calendar.setGridVisible(True)
        self.calendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setDateEditEnabled(False)
        self.calendar.setObjectName("calendar")
        self.Confirm = QtWidgets.QPushButton(Calendar)
        self.Confirm.setGeometry(QtCore.QRect(160, 270, 81, 61))
        self.Confirm.setObjectName("Confirm")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Calendar"))
        self.Confirm.setText(_translate("Calendar", "Đóng"))
import UI.pic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendar = QtWidgets.QWidget()
    ui = Ui_Calendar()
    ui.setupUi(Calendar)
    Calendar.show()
    sys.exit(app.exec_())
