# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdes\ChangePd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePD(object):
    def setupUi(self, ChangePD):
        ChangePD.setObjectName("ChangePD")
        ChangePD.resize(400, 342)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pic/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChangePD.setWindowIcon(icon)
        self.Confirm = QtWidgets.QPushButton(ChangePD)
        self.Confirm.setGeometry(QtCore.QRect(160, 270, 81, 61))
        self.Confirm.setObjectName("Confirm")
        self.label = QtWidgets.QLabel(ChangePD)
        self.label.setGeometry(QtCore.QRect(20, 20, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Timer = QtWidgets.QLabel(ChangePD)
        self.Timer.setGeometry(QtCore.QRect(10, 80, 381, 171))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.Timer.setFont(font)
        self.Timer.setFrameShape(QtWidgets.QFrame.Box)
        self.Timer.setText("")
        self.Timer.setAlignment(QtCore.Qt.AlignCenter)
        self.Timer.setObjectName("Timer")

        self.retranslateUi(ChangePD)
        QtCore.QMetaObject.connectSlotsByName(ChangePD)

    def retranslateUi(self, ChangePD):
        _translate = QtCore.QCoreApplication.translate
        ChangePD.setWindowTitle(_translate("ChangePD", "Bộ đếm"))
        self.Confirm.setText(_translate("ChangePD", "Đóng"))
        self.label.setText(_translate("ChangePD", "Thời gian chờ"))
import UI.pic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangePD = QtWidgets.QWidget()
    ui = Ui_ChangePD()
    ui.setupUi(ChangePD)
    ChangePD.show()
    sys.exit(app.exec_())
