# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdes\ShowStamp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowStamp(object):
    def setupUi(self, ShowStamp):
        ShowStamp.setObjectName("ShowStamp")
        ShowStamp.resize(960, 640)
        ShowStamp.setMinimumSize(QtCore.QSize(960, 640))
        ShowStamp.setMaximumSize(QtCore.QSize(960, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pic/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ShowStamp.setWindowIcon(icon)
        self.Confirm = QtWidgets.QPushButton(ShowStamp)
        self.Confirm.setGeometry(QtCore.QRect(440, 560, 81, 61))
        self.Confirm.setObjectName("Confirm")
        self.Stamp = QtWidgets.QLabel(ShowStamp)
        self.Stamp.setGeometry(QtCore.QRect(20, 20, 921, 521))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.Stamp.setFont(font)
        self.Stamp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Stamp.setText("")
        self.Stamp.setAlignment(QtCore.Qt.AlignCenter)
        self.Stamp.setObjectName("Stamp")

        self.retranslateUi(ShowStamp)
        QtCore.QMetaObject.connectSlotsByName(ShowStamp)

    def retranslateUi(self, ShowStamp):
        _translate = QtCore.QCoreApplication.translate
        ShowStamp.setWindowTitle(_translate("ShowStamp", "Tem"))
        self.Confirm.setText(_translate("ShowStamp", "Đóng"))
import UI.pic_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShowStamp = QtWidgets.QWidget()
    ui = Ui_ShowStamp()
    ui.setupUi(ShowStamp)
    ShowStamp.show()
    sys.exit(app.exec_())
